### ISSUE TITLE
[BUG] Icons in WPCasa Admin Dashboard are shifted

### ISSUE THREAD

**Issue by JoeHana** [wpsight/wpcasa#119]
## Prerequisites

- [x] I've read and tried everything from the [troubleshooting guide](https://docs.wpcasa.com/article/troubleshooting-guide/), but the issue persists.
- [x] I've experience in webdevelopment
- [ ] I'm new to WordPress
- [ ] I've already fixed/I'm going to fix this bug and have submitted/going to submit it as PR.

## Description
For some reason all the icons on the buttons are shifted in the WPCasa Admin Dashboard Panel (Check Screenshot below)
Checking the console it seems like this is caused by the following CSS from the wpsight-admin.min.css

```css
.wpsight-settings-page .wpsight-settings-wrap .settings_panel .wpsight-admin-ui-panel .button-text-icon span {
    position: relative;
    top: 11px;
    margin-right: 5px;
}
```

Removing the `top: 11px;` fixes this issue. However, I'm currently not sure why exactly this has been added in the first place. There must be a reason

## Screenshots and Attachments
![WPCasa-Settings-‹-WPCasa-London-—-WordPress](https://user-images.githubusercontent.com/122551/88313567-01b68400-cd14-11ea-8bff-5023e9a35c97.png)
